# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e054202f22eb2f315ae2697a6f1f681cb9e318571b911625488f4c8533d3a985aeb97e37327d5e35b069825d38bd0f005b23919844ba5c2a6f6576c466fbfce

test:
  secret_key_base: e72b345f915eab63f592666455f93d75c2bb688cdc2eea597987d4f08842906a2e9a2a480cc2afc69ebf8d0968c4636f07782d78ca164bba5138b172775dd621

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
